language: node_js
node_js:
- '10'
sudo: required
dist: trusty
addons:
  chrome: stable
  sonarcloud:
    organization: "$SONAR_KEY"
    token:
      secure: "$SONAR_TOKEN"
cache: npm
branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
  - PBI-84-documentation'
install:
- npm ci
script: skip
jobs: 
  include:
    - stage: release
      name: Build GitHub Release
      if: tag IS present
      script:
      - sudo dpkg --add-architecture i386
      - sudo apt-get -qq update
      - sudo apt-get install wine1.6
      - npm run lint
      - npm run release
      - npm run test
      - sonar-scanner -X
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file_glob: true
        file: dist/release/*
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      name: Deploy to Staging
      if: branch = develop
      script:
      - npm run lint
      - npm run build:staging
      - npm run test
      - sonar-scanner -X
      deploy:
        provider: pages
        target-branch: staging
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: false
        local-dir: dist/macroscope-kiosk
        on:
          branch: develop
    - stage: deploy
      name: Deploy to Production
      if: branch = master
      script:
      - npm run lint
      - npm run build:production
      - npm run test
      - sonar-scanner -X
      deploy:
        provider: pages
        target-branch: production
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: false
        local-dir: dist/macroscope-kiosk
        on:
          branch: master
    - stage: deploy
      name: Deploy compodoc to gh-pages
      if: branch = PBI-84-documentation
      script:
      - npm run compodoc
      deploy:
        provider: pages
        target-branch: gh-pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: false
        local-dir: dist/doc
        on:
          branch: PBI-84-documentation
notifications:
  slack:
    secure: YYJ5rzDaQjHrgKQeZmrjglaM7syTkhNplVS/SjXCOUPXWlsvOB65W/GBmlAZukgda3rNXYjH9SUMLXehJQGtUxZKXZxhjrVLID3sIdc576q6gV61wgp0tGcIfWqwuBkrgmkbGc+dwjYMPZDZYf+IqBQpSYVjgUileuBJ2QQu1TOtM5dSRv3PY6cXVgJcdienxn21udoYIDePuq9mdJnPtGmJivseGfFKQeV0p9fdesfsOMRQQHNnsLLTYk9uiuODk/Y9zK2sJ48n4nRw4PhwgIu/Fn8DqEuFlFteVw0EcnMStaBdv1z8hZg2CU8FledctqgRKL7VKrDYW22TE4pq9eyj0H7nulXTeSszOcbcNOpM4qPzR4JrYflBpXC2Fp+Z8exiaCKqd6uvR1MsSC0B/m+EK/jjFpZXBohRGIApN3czLjlCPBuOSSx/7v+Y3TLUS+X2JKksnoofVauHF230kEsKY/Bd0A17BTEJ2BP1XEzmDEPuZqFmE4q0UfcOetHvRfGDMlq0RNO0mSOUOZhia0Uzj3fVex2hm1bqtegeQlszBjtvb7At+mHHneKhKMZVTdcJoKb8n/rL8REsg5lNWnWU71UhUf9zCFwUplV0scIKWWJPXvAMCHMNOYUWQOy/0e7lzNEX/29jhZFf6QZn/6ziLhWYIHTi5rwZ7V3ntXQ=
